name: Update Reya Leaderboard Data

on:
  schedule:
    # Runs daily at 01:00 UTC
    - cron: '0 1 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Fetch latest leaderboard data
      run: |
        python fetch_complete_leaderboard.py
        
    - name: Check if data changed
      id: check_changes
      run: |
        if git diff --quiet reya_complete_leaderboard.json; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push changes
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add reya_complete_leaderboard.json
        git commit -m "🔄 Auto-update leaderboard data - $(date -u '+%Y-%m-%d %H:%M UTC')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: No changes detected
      if: steps.check_changes.outputs.changed == 'false'
      run: echo "No changes in leaderboard data, skipping commit"
